// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv2YOmiE2SuNoGAT0KLAOgGl4Pl7qWBFc',
    appId: '1:579451018541:web:4fc3627767edcdacd707a4',
    messagingSenderId: '579451018541',
    projectId: 'home-services-cf64c',
    authDomain: 'home-services-cf64c.firebaseapp.com',
    databaseURL: 'https://home-services-cf64c-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-cf64c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkygYCmg9jH5Z0OaRrxu65bJdjjCEuCQ',
    appId: '1:579451018541:android:47be66b7127e08a7d707a4',
    messagingSenderId: '579451018541',
    projectId: 'home-services-cf64c',
    databaseURL: 'https://home-services-cf64c-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-cf64c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxGraKunfxaXQ0KcoBObiZaH7yE_YFBU',
    appId: '1:579451018541:ios:9f8e5670543e9b66d707a4',
    messagingSenderId: '579451018541',
    projectId: 'home-services-cf64c',
    databaseURL: 'https://home-services-cf64c-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-cf64c.appspot.com',
    iosClientId: '579451018541-hs3c8tvtk3pv8k752ghu5p90006qesuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLxGraKunfxaXQ0KcoBObiZaH7yE_YFBU',
    appId: '1:579451018541:ios:9f8e5670543e9b66d707a4',
    messagingSenderId: '579451018541',
    projectId: 'home-services-cf64c',
    databaseURL: 'https://home-services-cf64c-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-cf64c.appspot.com',
    iosClientId: '579451018541-hs3c8tvtk3pv8k752ghu5p90006qesuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeService',
  );
}
